In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [3]:
data = pd.read_csv('nov-last-5-ach (4).csv', sep=',', index_col=0)
data.head()

,transaction_id,transaction_created_datetime,label_error_code,send_currency_symbol,receive_currency_symbol,user_state,payment_state,feature_transaction_usd_send,feature_local_receive,feature_kount_score,feature_kount_velocity,feature_sift_score,feature_days_since_first_completed,feature_six_month_send_limit,feature_account_type,feature_send_bank,feature_day_of_month,feature_customer_age,feature_previous_transactions
transaction_public_id,,,,,,,,,,,,,,,,,,,
R90279062553,8697171,2017-11-25 00:01:35,No Error,USD,INR,TUS_COMPLETED,Captured,2000.0,128760.00,38,2,0.0015,962.0,3600000,checking,FIRS,25.0,10455,38
R47511251183,8697173,2017-11-25 00:01:49,No Error,USD,INR,TUS_COMPLETED,Captured,2999.0,193075.62,41,0,0.1060,-5.0,1800000,checking,WELL,25.0,13176,1
R11421248445,8697197,2017-11-25 00:03:22,No Error,USD,INR,TUS_COMPLETED,Captured,1000.0,64380.00,36,0,0.0154,858.0,3600000,checking,FIRS,25.0,14177,18
R13938133386,8697218,2017-11-25 00:04:56,No Error,USD,INR,TUS_COMPLETED,Captured,3000.0,193140.00,30,0,0.0204,350.0,6000000,checking,TD B,25.0,13464,8
R74864872923,8697220,2017-11-25 00:05:05,No Error,USD,INR,TUS_COMPLETED,Captured,2999.0,193075.62,40,1,0.0387,771.0,1800000,checking,BANK,25.0,10456,22

In [4]:
data.columns

Index(['transaction_id', 'transaction_created_datetime', 'label_error_code',
       'send_currency_symbol', 'receive_currency_symbol', 'user_state',
       'payment_state', 'feature_transaction_usd_send',
       'feature_local_receive', 'feature_kount_score',
       'feature_kount_velocity', 'feature_sift_score',
       'feature_days_since_first_completed', 'feature_six_month_send_limit',
       'feature_account_type', 'feature_send_bank', 'feature_day_of_month',
       'feature_customer_age', 'feature_previous_transactions'],
      dtype='object')

In [5]:
X = data.filter(['feature_transaction_usd_send', 'feature_local_receive', 'feature_kount_score'])
X.head()

,feature_transaction_usd_send,feature_local_receive,feature_kount_score
transaction_public_id,,,
R90279062553,2000.0,128760.00,38
R47511251183,2999.0,193075.62,41
R11421248445,1000.0,64380.00,36
R13938133386,3000.0,193140.00,30
R74864872923,2999.0,193075.62,40

In [6]:
data.label_error_code.replace(['No Error', 'ACH_INSUFFICIENT_FUNDS'], [1, 0], inplace=True)
y = data.filter(['label_error_code'])
y.head()

                       label_error_code
transaction_public_id
R90279062553                          1
R47511251183                          1
R11421248445                          1
R13938133386                          1
R74864872923                          1

In [7]:
#X, y = make_classification(n_samples=1000, n_features=4,
#                           n_informative=2, n_redundant=0,
#                           random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [8]:
clf.fit(X, y.values.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [9]:
print(clf.feature_importances_)

[ 0.22168877  0.48344681  0.29486443]

In [10]:
print(clf.predict([[1700, 109446, 0]]))

[1]